[package]
name = "valid8r_derive"
description = "Proc macro that provides `#[derive(Validate)]` for the `valid8r` crate."
authors.workspace = true
version.workspace = true
edition.workspace = true
publish.workspace = true


[lib]
proc-macro = true

[dependencies]
syn = "3"
quote = "1"
proc-macro2 = "1"
proc-macro-error2 = "2"
darling = { version = "0.24", features = ["suggestions"] }
phonenumber.workspace = true
